### PR TITLE
[refactor] puzzle2 improvements

### PR DESCRIPTION
**Pull request by mwpodgorni**

### CODE REVIEW

**Comment by mwpodgorni** [comment]
[Puzzle2 - Fourth Iteration](https://trello.com/c/k8m8Pzmc/84-puzzle2-fourth-iteration)

**Comment by mwpodgorni** [comment]
[Puzzle2: Lerp hand to clock](https://trello.com/c/hpuzHjwM/63-puzzle2-lerp-hand-to-clock)

**Review by alexw-su — APPROVED** [review]
lgtm

**Review by MarcVonGlahn — APPROVED** [review]
lgtm

**Pull request merged**
