### PR TITLE
[feat:] Teleport transition

### PR DESCRIPTION
**Pull request by alexw-su**

### CODE REVIEW

**Review by MarcVonGlahn — APPROVED** [review]
Should be good :D

**Comment by alexw-su** [comment]
[Create a nice effect when entering, leaving paintings](https://trello.com/c/TLrObZoM/44-create-a-nice-effect-when-entering-leaving-paintings)

**Comment by alexw-su** [comment]
[Create a nice effect when entering, leaving paintings](https://trello.com/c/TLrObZoM/44-create-a-nice-effect-when-entering-leaving-paintings)

**Comment by alexw-su** [comment]
[Create a nice effect when entering, leaving paintings](https://trello.com/c/TLrObZoM/44-create-a-nice-effect-when-entering-leaving-paintings)

**Pull request merged**
