### PR TITLE
[refactor]: Restructured the puzzle 1 prefab

### PR DESCRIPTION
**Pull request by alexw-su**

### CODE REVIEW

**Review by mwpodgorni — APPROVED** [review]

**Comment by alexw-su** [comment]
[Puzzle 1 second iteration](https://trello.com/c/Jf1LqqFX/55-puzzle-1-second-iteration)

**Comment by alexw-su** [comment]
[Puzzle 1 second iteration](https://trello.com/c/Jf1LqqFX/55-puzzle-1-second-iteration)

**Comment by alexw-su** [comment]
[Puzzle 1 second iteration](https://trello.com/c/Jf1LqqFX/55-puzzle-1-second-iteration)

**Comment by mwpodgorni** [comment]
[standardize structure of each puzzle object (names, groups etc.)](https://trello.com/c/LGmMi2tY/47-standardize-structure-of-each-puzzle-object-names-groups-etc)

**Pull request merged**
