### PR TITLE
[refactor] Map improvements

### PR DESCRIPTION
**Pull request by mwpodgorni**

### CODE REVIEW

**Review by alexw-su — APPROVED** [review]
poggers!!! it's looking good!
poggers

**Review by alexw-su — APPROVED** [review]
POGGERS IT'S EVEN BETTER
[](https://linkvertise.com/991133/ada61?o=sharing)

**Review by alexw-su — APPROVED** [review]
okay all good now

**Comment by mwpodgorni** [comment]
[make a script for randomizing tree size + general tree improvements](https://trello.com/c/dZd9Jgaz/68-make-a-script-for-randomizing-tree-size-general-tree-improvements)

**Pull request merged**
